#!/usr/bin/env bash
# Configure a new Ubuntu machine by installing Nginx,
# setting it to listen on port 80, serving a "Hello World" page,
# setting up a redirect to a YouTube video, and creating a custom 404 page.

set -euo pipefail

echo "Updating and installing Nginx..."
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

echo "Setting up Nginx and firewall..."
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

echo "Configuring ownership and permissions..."
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Creating 'Hello World' page..."
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Setting up redirection to a YouTube video..."
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Creating custom 404 page..."
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

echo "Restarting Nginx..."
sudo service nginx restart

echo "Completed. Nginx setup finished!"

