#!/usr/bin/env bash
# Find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
